var token = 'eyJhbGciOiJSUzI1NiIsImtpZCI6IjJEMDQwODBDNUNBQzhCNEZEQjAyRDEwRDBBOTFCOERBREQzQzBFRDUiLCJ0eXAiOiJhdCtqd3QiLCJ4NXQiOiJMUVFJREZ5c2kwX2JBdEVOQ3BHNDJ0MDhEdFUifQ.eyJuYmYiOjE3MzEwNjEzNzgsImV4cCI6MTczMTA2MjI3OCwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5lbWVhMWIuZmVuZXJnb3guY29tIiwiYXVkIjoiRmVuZXJnby5OZWJ1bGEuQXV0aG9yaXplciIsImNsaWVudF9pZCI6InZpc3RyYS1zZGxjLWRldiIsImNsaWVudF90ZW5hbnQiOiIxY2YxYmY2ZS02Y2EzLTRmODMtOTZmNS0wNmU3Y2U2NDJlYTYiLCJpYXQiOjE3MzEwNjEzNzgsInNjb3BlIjpbImZlbnguYWxsIl19.i33bnsFqFTN91dtLEqkedIAVDpaGsWS8ogmVb2aLmTDclWKSm3dX-imNNcx6xfkw6MYqmHLYeDcrBjcN3dWTZEfl3ezoqOzlgiLavUOSzUj2cIMGkxLlkUKunPHt2OnvxmsnNhAPV6DZBgAcn5Kaflj6kiZHDqFFSLgv0X1P0BTsg-A5wJnstTR6aHYjL0qSBLdzluTRwNaHl57BjOFpQorVq32R4EizfBXHWPqDo-tTSDjlliSRNKQkrxDgw-IQ9S67sfhuc2gFoEOEZhvG8a5ywxUzRBfb8udIAqQRukjmb6Vypi4jtR-ErG29vF_NGYtjVMMhNbZD5S62TtKMkg'

var companyCollectionPath = ''
var indidualCollectionPath = ''

var envFile = ''

var iterationDataForIndividual = ''
var iterationDataForCompany = ''

console.log()